title: Jacob Hummel
email: j4cobhummel@gmail.com
description: >
  Jacob Hummel, Web and Mobile Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jacobhummel.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass

permalink: pretty

# gems:
#   - bootstrap-sass
